In [152]:
# Import Library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [153]:
# Membaca DataFrame
df = pd.read_csv('bakery_sales.csv')
df

       Transaction           Item         date_time period_day weekday_weekend
0                1          Bread   10/30/2016 9:58    morning         weekend
1                2   Scandinavian  10/30/2016 10:05    morning         weekend
2                2   Scandinavian  10/30/2016 10:05    morning         weekend
3                3  Hot chocolate  10/30/2016 10:07    morning         weekend
4                3            Jam  10/30/2016 10:07    morning         weekend
...            ...            ...               ...        ...             ...
20502         9682         Coffee    4/9/2017 14:32  afternoon         weekend
20503         9682            Tea    4/9/2017 14:32  afternoon         weekend
20504         9683         Coffee    4/9/2017 14:57  afternoon         weekend
20505         9683         Pastry    4/9/2017 14:57  afternoon         weekend
20506         9684      Smoothies    4/9/2017 15:04  afternoon         weekend

[20507 rows x 5 columns]

In [154]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20507 entries, 0 to 20506
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Transaction      20507 non-null  int64
 1   Item             20507 non-null  object
 2   date_time        20507 non-null  object
 3   period_day       20507 non-null  object
 4   weekday_weekend  20507 non-null  object
dtypes: int64(1), object(4)
memory usage: 801.2+ KB

In [155]:
df.isnull().sum()

Transaction        0
Item               0
date_time          0
period_day         0
weekday_weekend    0
dtype: int64

In [156]:
transactions = df.groupby('Transaction')['Item'].apply(list)
transactions

Transaction
1                                                 [Bread]
2                            [Scandinavian, Scandinavian]
3                           [Hot chocolate, Jam, Cookies]
4                                                [Muffin]
5                                 [Coffee, Pastry, Bread]
                              ...
9680                                              [Bread]
9681    [Truffles, Tea, Spanish Brunch, Christmas common]
9682                  [Muffin, Tacos-Fajita, Coffee, Tea]
9683                                     [Coffee, Pastry]
9684                                          [Smoothies]
Name: Item, Length: 9465, dtype: object

In [157]:
from mlxtend.preprocessing import TransactionEncoder

te = TransactionEncoder()
te_data = te.fit(transactions).transform(transactions)
df = pd.DataFrame(te_data, columns=te.columns_)

In [219]:
from mlxtend.frequent_patterns import apriori, association_rules

# Tentukan minimum support
frequent_itemsets = apriori(df, min_support=0.02, use_colnames=True)

# Tentukan aturan asosiasi dengan confidence tertentu
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.1)

In [192]:
frequent_itemsets

     support                 itemsets
0   0.036344              (Alfajores)
1   0.327205                  (Bread)
2   0.040042                (Brownie)
3   0.103856                   (Cake)
4   0.478394                 (Coffee)
5   0.054411                (Cookies)
6   0.039197             (Farm House)
7   0.058320          (Hot chocolate)
8   0.038563                  (Juice)
9   0.061807              (Medialuna)
10  0.038457                 (Muffin)
11  0.086107                 (Pastry)
12  0.071844               (Sandwich)
13  0.029054           (Scandinavian)
14  0.034548                  (Scone)
15  0.034443                   (Soup)
16  0.142631                    (Tea)
17  0.033597                  (Toast)
18  0.020285               (Truffles)
19  0.023349            (Cake, Bread)
20  0.090016          (Coffee, Bread)
21  0.029160          (Bread, Pastry)
22  0.028104             (Tea, Bread)
23  0.054728           (Cake, Coffee)
24  0.023772              (Tea, Cake)
25  0.028209        (Coffee, Cookies)
26  0.029583  (Coffee, Hot chocolate)
27  0.020602          (Coffee, Juice)
28  0.035182      (Medialuna, Coffee)
29  0.047544         (Coffee, Pastry)
30  0.038246       (Sandwich, Coffee)
31  0.049868            (Tea, Coffee)
32  0.023666          (Coffee, Toast)

In [220]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(Cake),(Bread),0.103856,0.327205,0.023349,0.224822,0.687097,-0.010633,0.867923,-0.336947
1,(Coffee),(Bread),0.478394,0.327205,0.090016,0.188163,0.575059,-0.066517,0.828731,-0.586210
2,(Bread),(Coffee),0.327205,0.478394,0.090016,0.275105,0.575059,-0.066517,0.719561,-0.523431
3,(Pastry),(Bread),0.086107,0.327205,0.029160,0.338650,1.034977,0.000985,1.017305,0.036980
4,(Tea),(Bread),0.142631,0.327205,0.028104,0.197037,0.602181,-0.018566,0.837890,-0.435198
5,(Cake),(Coffee),0.103856,0.478394,0.054728,0.526958,1.101515,0.005044,1.102664,0.102840
6,(Coffee),(Cake),0.478394,0.103856,0.054728,0.114399,1.101515,0.005044,1.011905,0.176684
7,(Tea),(Cake),0.142631,0.103856,0.023772,0.166667,1.604781,0.008959,1.075372,0.439556
8,(Cake),(Tea),0.103856,0.142631,0.023772,0.228891,1.604781,0.008959,1.111865,0.420538
9,(Cookies),(Coffee),0.054411,0.478394,0.028209,0.518447,1.083723,0.002179,1.083174,0.081700
10,(Hot chocolate),(Coffee),0.058320,0.478394,0.029583,0.507246,1.060311,0.001683,1.058553,0.060403
11,(Juice),(Coffee),0.038563,0.478394,0.020602,0.534247,1.116750,0.002154,1.119919,0.108738
12,(Medialuna),(Coffee),0.061807,0.478394,0.035182,0.569231,1.189878,0.005614,1.210871,0.170091
13,(Pastry),(Coffee),0.086107,0.478394,0.047544,0.552147,1.154168,0.006351,1.164682,0.146161
14,(Sandwich),(Coffee),0.071844,0.478394,0.038246,0.532353,1.112792,0.003877,1.115384,0.109205
15,(Tea),(Coffee),0.142631,0.478394,0.049868,0.349630,0.730840,-0.018366,0.802014,-0.300482
16,(Coffee),(Tea),0.478394,0.142631,0.049868,0.104240,0.730840,-0.018366,0.957142,-0.413856
17,(Toast),(Coffee),0.033597,0.478394,0.023666,0.704403,1.472431,0.007593,1.764582,0.332006